### ISSUE TITLE
No RSS for Event Manager

### ISSUE THREAD

**Issue by rohit1290** [ColdTrick/event_manager#101]
I am using Elgg 2.2.2 with Event Manager Version	5.0.1 plugin. I have around 100+ events on my website, but when I try to view the rss of events, there is no data available. I can see that the rss properties are getting generated properly but the data is not show in that rss view.

Screenshot showing the events on my elgg

![capture_01](https://cloud.githubusercontent.com/assets/2772844/25304853/6c1bd1a4-278d-11e7-8be0-611548aa6245.PNG)

Screenshot showing RSS view

![capture_02](https://cloud.githubusercontent.com/assets/2772844/25304854/74bb790e-278d-11e7-9882-6064471edfec.PNG)

**Comment by jdalsem** [comment]
i can confirm that i have the same issue and i will look into it

**Comment by jdalsem** [comment]
Elgg 3 version of this plugin will no longer have this problem
