### ISSUE TITLE
non logged in registered user icons are not displayed in the attendees list

### ISSUE THREAD

**Issue by oseg** [ColdTrick/event_manager#103]
Context: elgg v2.3.3 + event manager v8.1.1

Scenario:
- log in elgg (admin or not)
- Create a public event with following options enabled:
  - Allow not-loggedin users to register
  - Display attendees
- register to this event
- log out and register to this event: enter an email and name (olivier in the screenshot) and follow registration process
- look at this event attendees list 

=> there are 2 attendees in the list: the 1st attendee (logged in user) icon is displayed, whereas the 2nd attendee (non logged in user) icon is not displayed. His name is displayed instead (see screenshot).

![image](https://cloud.githubusercontent.com/assets/15892521/26247885/30597cac-3ca0-11e7-9a56-7e3c52c5f896.png)

**Comment by oseg** [comment]
To workaround (fix) the issue, add missing "vendor/elgg/elgg/" path in lines 37 & 38 of views/default/icon/object/eventregistration.php file:

```
$result .= "<img style='background: url(" . elgg_get_site_url() . "vendor/elgg/elgg/_graphics/icons/user/default" . $vars["size"] . ".gif) no-repeat scroll 0% 0% transparent;'";
$result .= " src='" . elgg_get_site_url() . "vendor/elgg/elgg/_graphics/spacer.gif'";
```

**Comment by michelesbw** [comment]
I saw the same thing, could this fix be merged into repo? :)

**Comment by michelesbw** [comment]
Thanks @oseg that worked fine for me as well!
