### ISSUE TITLE
if an event location address contains a single quote, the google map view is not displayed

### ISSUE THREAD

**Issue by oseg** [ColdTrick/event_manager#105]
Context:
--------
- elgg v2.3.3
- event manager v8.1.1

Scenario:
---------
- Create an event
- Fill in the mandatory fields: title, start and end dates
- In the location section, click on the "Configure" button
- Click on the location text field
- In the popup location address field, enter an address containing a single quote (for instance "Rue Quai de l'Horloge, Montréal, QC H3C, Canada")
- Click on the "save" button

Results:
--------
The event google map view is not displayed

**Comment by oseg** [comment]
I wrote a potential fix for this bug which support location addresses which contain single or double quotes: https://github.com/ColdTrick/event_manager/pull/104

**Comment by jdalsem** [comment]
This is not an issue in the latest master version of this plugin (it might be solved earlier, but it is unknown when)
