### ISSUE TITLE
ERROR: object/elements/full expects an ElggEntity in $vars['entity']

### ISSUE THREAD

**Issue by rohit1290** [ColdTrick/event_manager#106]
I was getting the following error in my elgg error_log file (Elgg 2.3.3):
`ERROR: object/elements/full expects an ElggEntity in $vars['entity']`

Then I found that in the file "view.php" [event_manager/views/default/event_manager/event] the entity parameter is missing for the elgg_view of 'object/elements/full'

You can fix the issue for the next release.

**Comment by jdalsem** [comment]
It is already fixed in https://github.com/ColdTrick/event_manager/commit/e6397ad02595338365878c46f0df1b9b128c73fc

This fixed is part of v8.0 and higher

**Comment by rohit1290** [comment]
Oops..!! I saw version 5.0.1 on elgg site and I was still using that plugin with Elgg 2.3.3. 
I didn't knew that the plugin has evolved till version 8.1.
