### ISSUE TITLE
Contact details exceed sidebar's width

### ISSUE THREAD

**Issue by michelesbw** [ColdTrick/event_manager#107]
Hello,
don't know if it's our theme fault but Contact details exceed sidebar's width, see screenshot below.
Cheers

<img width="174" alt="screen-event-manager" src="https://user-images.githubusercontent.com/5203511/28130934-b0be0558-6738-11e7-9188-24e3384de5cc.png">

**Comment by michelesbw** [comment]
It looks like the culprit is "Website" field, if empty width respects column's

**Comment by jdalsem** [comment]
Yeah the reason is probably wordwrapping as the website is one word and it probably is not allowed to break a word.

**Comment by michelesbw** [comment]
Humble suggestion: remove from sidebar and put it in main body area, sidebars are not always seen and in mobile views are often at the bottom... ;)

**Comment by jdalsem** [comment]
Default Elgg theme and also Aalborg break the word. So i expect the issue is part of your theme

![afbeelding](https://user-images.githubusercontent.com/861833/28171471-cfc9490c-67e8-11e7-8c65-711535c66894.png)

**Comment by michelesbw** [comment]
Hmmm sorry for wasting your time :(

**Comment by jdalsem** [comment]
not a problem. if it was a bug of event_manager i would have fixed it and would be very grateful for you reporting this issue.

**Comment by michelesbw** [comment]
Still would like to be able to understand exactly what the problem is not to bother you devs :S 
Thanks for your kindness as always!

**Comment by jdalsem** [comment]
Checked your site and maybe there is a bit more to it... will examine if i can reproduce it locally

**Comment by jdalsem** [comment]
Still think the problem is in your theme. There is a css rule for
`.elgg-sidebar .elgg-module` that sets the display to inline-block. Removing the rule solves the problem, but i do not know why it is there. I believe core and aalborg do not have this rule.
