### ISSUE TITLE
Listing of events in order of event day instead of creation time

### ISSUE THREAD

**Issue by gerard-kanters** [ColdTrick/event_manager#111]
Events are sorted by creation time (elgg default). From a user perspective it is best to see events in order of start time of the event. So upcoming events first.

**Comment by jdalsem** [comment]
events should be ordered by start of the event (see https://github.com/ColdTrick/event_manager/blob/master/lib/functions.php#L92)... whenor where are you experiencing a different sort order?

**Comment by gerard-kanters** [comment]
I see that it should, but it doesn't. I still see the list in order of creation time (I did check past events since there were no events planned in the future). But that should not make a difference since sorting is done for all options the same. Maybe it is related how the date is stored in the database ?

**Comment by jdalsem** [comment]
date/time is stored as timestamps, so they are ints... that should be no problem to sort... there was/is an upgrade that changed how timestamps are stored. That upgrade should upgrade old storage to a new version. Maybe something went wrong for those items... could you test by creating 2 new events where the second created event starts before the first created and see if those items are sorted correctly?

**Comment by gerard-kanters** [comment]
I will check.

**Comment by jdalsem** [comment]
Do you have any more information regarding this issue? I will reopen if you have
