### ISSUE TITLE
This page didn't load Google Maps correctly. See the JavaScript console for technical details.

### ISSUE THREAD

**Issue by agencetca** [ColdTrick/event_manager#114]
Hi. The Location field throws a type error in the browser

> TypeError: d is undefined

![capture du 2018-04-14 19-05-45](https://user-images.githubusercontent.com/17163279/38770782-7976b356-4018-11e8-9dbd-452a76fe831c.png)

This is google-map related, how could this be fixed?

**Comment by jdalsem** [comment]
are you using the latest version? does the console log show any error?

**Comment by jdalsem** [comment]
Closing due to lack of information...
