### ISSUE TITLE
RSS view not working on activity page

### ISSUE THREAD

**Issue by oseg** [ColdTrick/event_manager#115]
Context: elgg v2.3.7, event_manager v9.2

Scenario:
- Log in as 'admin'
- Create a 'Test Event' event
- Go to activity page => 'admin created event Test Event' is displayed
- Click on "RSS feed for this page" button
=> Crash

Callstack:
PHP Fatal error:  Maximum function nesting level of '100' reached, aborting! in C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php on line 100
PHP Stack trace:
PHP   1. {main}() C:\xampp\htdocs\elgg-2.3.7\index.php:0
PHP   2. Elgg\Application::index() C:\xampp\htdocs\elgg-2.3.7\index.php:8
PHP   3. Elgg\Application->run() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\Application.php:384
PHP   4. Elgg\Router->route() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\Application.php:436
PHP   5. call_user_func:{C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\Router.php:100}() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\Router.php:100
PHP   6. _elgg_river_page_handler() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\Router.php:100
PHP   7. elgg_view_resource() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\lib\river.php:695
PHP   8. Elgg\ViewsService->renderView() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\lib\views.php:518
PHP   9. Elgg\ViewsService->renderViewFile() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:306
PHP  10. include() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:370
PHP  11. elgg_list_river() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\views\default\resources\river.php:56
PHP  12. elgg_view() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\lib\river.php:482
PHP  13. Elgg\ViewsService->renderView() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\lib\views.php:337
PHP  14. Elgg\ViewsService->renderViewFile() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:306
PHP  15. include() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:370
PHP  16. elgg_view_list_item() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\views\rss\page\components\list.php:12
PHP  17. elgg_view_river_item() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\lib\views.php:1564
PHP  18. elgg_view() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\lib\views.php:1303
PHP  19. Elgg\ViewsService->renderView() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\lib\views.php:337
PHP  20. Elgg\ViewsService->renderViewFile() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:306
PHP  21. include() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:370
PHP  22. elgg_view() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\views\rss\river\item.php:13
PHP  23. Elgg\ViewsService->renderView() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\lib\views.php:337
PHP  24. Elgg\ViewsService->renderViewFile() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:306
PHP  25. include() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:370
PHP  26. elgg_view() C:\xampp\htdocs\elgg-2.3.7\mod\event_manager\views\default\river\object\event\create.php:2
PHP  27. Elgg\ViewsService->renderView() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\lib\views.php:337
PHP  28. Elgg\ViewsService->renderViewFile() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:306
PHP  29. include() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:370
PHP  30. elgg_view() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\views\rss\river\item.php:13
PHP  31. Elgg\ViewsService->renderView() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\lib\views.php:337
PHP  32. Elgg\ViewsService->renderViewFile() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:306
PHP  33. include() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:370
PHP  34. elgg_view() C:\xampp\htdocs\elgg-2.3.7\mod\event_manager\views\default\river\object\event\create.php:2
PHP  35. Elgg\ViewsService->renderView() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\lib\views.php:337
PHP  36. Elgg\ViewsService->renderViewFile() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:306
PHP  37. include() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:370
PHP  38. elgg_view() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\views\rss\river\item.php:13
PHP  39. Elgg\ViewsService->renderView() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\lib\views.php:337
PHP  40. Elgg\ViewsService->renderViewFile() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:306
PHP  41. include() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:370
PHP  42. elgg_view() C:\xampp\htdocs\elgg-2.3.7\mod\event_manager\views\default\river\object\event\create.php:2
PHP  43. Elgg\ViewsService->renderView() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\lib\views.php:337
PHP  44. Elgg\ViewsService->renderViewFile() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:306
PHP  45. include() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:370
PHP  46. elgg_view() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\views\rss\river\item.php:13
PHP  47. Elgg\ViewsService->renderView() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\lib\views.php:337
PHP  48. Elgg\ViewsService->renderViewFile() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:306
PHP  49. include() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:370
PHP  50. elgg_view() C:\xampp\htdocs\elgg-2.3.7\mod\event_manager\views\default\river\object\event\create.php:2
PHP  51. Elgg\ViewsService->renderView() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\lib\views.php:337
PHP  52. Elgg\ViewsService->renderViewFile() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:306
PHP  53. include() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:370
PHP  54. elgg_view() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\views\rss\river\item.php:13
PHP  55. Elgg\ViewsService->renderView() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\lib\views.php:337
PHP  56. Elgg\ViewsService->renderViewFile() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:306
PHP  57. include() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:370
PHP  58. elgg_view() C:\xampp\htdocs\elgg-2.3.7\mod\event_manager\views\default\river\object\event\create.php:2
PHP  59. Elgg\ViewsService->renderView() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\lib\views.php:337
PHP  60. Elgg\ViewsService->renderViewFile() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:306
PHP  61. include() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:370
PHP  62. elgg_view() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\views\rss\river\item.php:13
PHP  63. Elgg\ViewsService->renderView() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\lib\views.php:337
PHP  64. Elgg\ViewsService->renderViewFile() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:306
PHP  65. include() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:370
PHP  66. elgg_view() C:\xampp\htdocs\elgg-2.3.7\mod\event_manager\views\default\river\object\event\create.php:2
PHP  67. Elgg\ViewsService->renderView() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\lib\views.php:337
PHP  68. Elgg\ViewsService->renderViewFile() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:306
PHP  69. include() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:370
PHP  70. elgg_view() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\views\rss\river\item.php:13
PHP  71. Elgg\ViewsService->renderView() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\lib\views.php:337
PHP  72. Elgg\ViewsService->renderViewFile() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:306
PHP  73. include() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:370
PHP  74. elgg_view() C:\xampp\htdocs\elgg-2.3.7\mod\event_manager\views\default\river\object\event\create.php:2
PHP  75. Elgg\ViewsService->renderView() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\lib\views.php:337
PHP  76. Elgg\ViewsService->renderViewFile() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:306
PHP  77. include() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:370
PHP  78. elgg_view() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\views\rss\river\item.php:13
PHP  79. Elgg\ViewsService->renderView() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\lib\views.php:337
PHP  80. Elgg\ViewsService->renderViewFile() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:306
PHP  81. include() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:370
PHP  82. elgg_view() C:\xampp\htdocs\elgg-2.3.7\mod\event_manager\views\default\river\object\event\create.php:2
PHP  83. Elgg\ViewsService->renderView() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\lib\views.php:337
PHP  84. Elgg\ViewsService->renderViewFile() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:306
PHP  85. include() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:370
PHP  86. elgg_view() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\views\rss\river\item.php:13
PHP  87. Elgg\ViewsService->renderView() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\lib\views.php:337
PHP  88. Elgg\ViewsService->renderViewFile() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:306
PHP  89. include() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:370
PHP  90. elgg_view() C:\xampp\htdocs\elgg-2.3.7\mod\event_manager\views\default\river\object\event\create.php:2
PHP  91. Elgg\ViewsService->renderView() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\lib\views.php:337
PHP  92. Elgg\ViewsService->renderViewFile() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:306
PHP  93. include() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:370
PHP  94. elgg_view() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\views\rss\river\item.php:13
PHP  95. Elgg\ViewsService->renderView() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\lib\views.php:337
PHP  96. Elgg\ViewsService->renderViewFile() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:306
PHP  97. include() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:370
PHP  98. elgg_view() C:\xampp\htdocs\elgg-2.3.7\mod\event_manager\views\default\river\object\event\create.php:2
PHP  99. Elgg\ViewsService->renderView() C:\xampp\htdocs\elgg-2.3.7\vendor\elgg\elgg\engine\lib\views.php:337

**Comment by jdalsem** [comment]
Fixed by https://github.com/ColdTrick/event_manager/commit/b97836f9473222b0392253b87d3ca88e7fdd3a5b
