### ISSUE TITLE
Public group events could be accessible whereas group setting is set to 'members only'

### ISSUE THREAD

**Issue by oseg** [ColdTrick/event_manager#117]
Context: elgg v2.3.7 & event_manager v9.2

Scenario:
- Create  a 'test group' with following settings:
  - set 'Who can see this group?' to 'logged in users' and
  - set 'Accessibility of group content' to 'Unrestricted'
- Create a 'public event' in the 'test group' with access level set to 'Public'
- Change the 'test group' settings:
  - set 'Accessibility of group content' to 'members only'
- log in as another user not member of the 'test group'
- try to access to the 'public event' through 'Events' menu item or through 'Public event' url
=> the error message "You must be a member of this group to view the requested page" is displayed
- log out
- try to access to the 'public event' through 'Events' menu item or through 'Public event' url
=> the 'public event' is accessible, whereas the group settings is set to 'members only'

**Comment by jdalsem** [comment]
The situation is unwanted. Being able to create this situation is a generic problem. This has been reported by you here https://github.com/Elgg/Elgg/issues/10285 and will no longer be achievable in Elgg 3.0
