### ISSUE TITLE
Elgg 3: Swap Event Banner and Event Date Display

### ISSUE THREAD

**Issue by rohit1290** [ColdTrick/event_manager#138]
I believe that the banner should be below the date segment i.e. first the Date and Time should appear then the banner.

![screenshot from 2018-11-27 23-29-04](https://user-images.githubusercontent.com/2772844/49101466-46b6b880-f29c-11e8-8222-f4cfe3cc2761.png)

**Comment by jdalsem** [comment]
That kind of big image is not intended... a more banner like image should appear. Maybe you ran into a bug when uploading the image. Are you experiencing the same problem with the latest versions?

**Comment by rohit1290** [comment]
> That kind of big image is not intended... a more banner like image should appear.

Well this is my local setup for testing. If I upload a banner type image then it will appear better. but the issue is not with the image being square or banner.

> Are you experiencing the same problem with the latest versions?

The issue ticket was created because the date is appearing below the image. I cannot restrict my user to upload a square or banner type image. I was suggesting that the date div i.e., "Wednesday, November 28, 2018" should appear above the image div. It will look more clean and logical.
I have tested the latest code as well and still the image is appearing above the date.

**Comment by jdalsem** [comment]
it is intended that the uploaded image is resized/cropped automatically to be more banner like. That should happen. It might be a bug that it does not happen (#141). Did you just update both Elgg and event manager in the last 10 minutes?

**Comment by rohit1290** [comment]
> Did you just update both Elgg and event manager in the last 10 minutes?

Elgg version: 3.0rc2
Event Manger version: Zip download from github master branch i.e. changes covered till 85942a4 (last commit of master branch)

**Comment by jdalsem** [comment]
Using latest dev branches from event manager and Elgg core i cannot reproduce the problem. Uploading square images still result in a banner like cutout.
![image](https://user-images.githubusercontent.com/861833/51593656-fa31d700-1ef2-11e9-90bc-99335a4320ad.png)

**Comment by rohit1290** [comment]
Ok.. I found the problem.
You are assuming that elgg admin is using the default elgg theme and hence the square image will look like banner. In my case with default theme the image resolution will be 928x300
However, I am using a custom theme with a narrow column width. In my case with my custom theme the image resolution in 500x300

In both the case the height remain the same i.e. 300px. This is the reason square image is not appearing as banner with my theme.

**Comment by rohit1290** [comment]
There should be check in the plugin itself that will auto calculate the height of the image as 1/3 of the div's width so that the banner thing works with any theme.
