### ISSUE TITLE
Elgg 3: Attend button missing

### ISSUE THREAD

**Issue by PerJensen** [ColdTrick/event_manager#151]
If you set an end date for attendance, the Attend button is not displayed.

**Comment by PerJensen** [comment]
I was wrong here, sorry. The Attend button is displayed until the end date.

The bug is that the text added in the field "Text when the event registration is completed" is not displayed.

**Comment by jdalsem** [comment]
This text will only show if there is a registration process, so if there is no program or registration questions, this text will no show

**Comment by PerJensen** [comment]
Ahh, I see. Just thought the buttons would be replaced, when registration ended (closed), by an entered text like, Registration closed.

**Comment by jdalsem** [comment]
Updated the text so it should be clearer this is regarding the text displayed when a user finishes the registration
