### ISSUE TITLE
Elgg 3: Google maps not working

### ISSUE THREAD

**Issue by PerJensen** [ColdTrick/event_manager#152]
When you click the location field, the map opens as it should in a window, but when you type an address and click search, nothing happens.

**Comment by jdalsem** [comment]
anything in the browser development console?

**Comment by PerJensen** [comment]
Nothing in console. It's like the button does not work!

Just noticed. When I click the search button nothing happens like I mentioned, but if i click the search field and press enter, then the save button appears and the map focus on the entered address. But then, when clicking the save button nothing happens?

**Comment by jdalsem** [comment]
Does switching to the other map engine works?

**Comment by PerJensen** [comment]
Yes, osm works as expected.

**Comment by PerJensen** [comment]
I have now tested version 10.0.1 and 11.0 in a fresh Elgg 3.2.0 installation. Unfortunately, google maps still don't work. I'm testing on localhost.

**Comment by mendo79** [comment]
I have the same Problem, tested on Elgg 3.3.1
version 10.0.1 - google maps don't work
version 11.0.1 - google maps don't work and calnder view for events is empty

it would be great to have location autocomplete, please

**Comment by jdalsem** [comment]
Fixed in https://github.com/ColdTrick/event_manager/commit/51c334b8ccf68153fad3bdcdcc7ab2fddc287f88
