### ISSUE TITLE
pdf: No config found

### ISSUE THREAD

**Issue by PerJensen** [ColdTrick/event_manager#153]
When I try to "Save as pdf", I get the no config error. Bug or is there anything I need to configure for this to work?

**Comment by jdalsem** [comment]
did you install the plugin via composer or downloaded the zip from github or elgg.org?

**Comment by PerJensen** [comment]
From github, normal plugin install.

**Comment by jdalsem** [comment]
unable to reproduce at the moment... did you download a release from github or just the latest code?

**Comment by PerJensen** [comment]
Hmmm, probably with latest code. Just tried with latest release and it's working. Sorry.
(google maps still not working though)

**Comment by jdalsem** [comment]
ok.. will close it then
