### ISSUE TITLE
Event Form

### ISSUE THREAD

**Issue by andrewga** [ColdTrick/event_manager#154]
Is it possible to add a feature to have the post event form already expanded?  Instead of the user having to press configure on each box.

**Comment by jdalsem** [comment]
not with a setting... but if you change `true` to `false` on this line https://github.com/ColdTrick/event_manager/blob/6ca98753104e6b27a443d0f9b5c2f81a7e6889a3/views/default/forms/event_manager/event/module.php#L6, they will be open by default

**Comment by andrewga** [comment]
Perfect! Thanks so much!
