### ISSUE TITLE
elgg 3.3.7 Event Manager v12 add/edit Location - Search and Save Button onclik don't work

### ISSUE THREAD

**Issue by mendo79** [ColdTrick/event_manager#160]
hi, i found a solution for this Problem, just change 2 times "input" to "button" in File:

event_manager/views/default/event_manager/maps/google/location_input.js

old: $(document).on('click', '#event-manager-edit-maps-search-container input[name="address_search_submit"]', function() {
new:$(document).on('click', '#event-manager-edit-maps-search-container button[name="address_search_submit"]', function() {	

old: $(document).on('click', '#event-manager-edit-maps-search-container input[name="address_search_save"]', function() {
new:$(document).on('click', '#event-manager-edit-maps-search-container button[name="address_search_save"]', function() {

**Comment by mendo79** [comment]
it solved

**Comment by jdalsem** [comment]
Fixed in https://github.com/ColdTrick/event_manager/commit/51c334b8ccf68153fad3bdcdcc7ab2fddc287f88
