### ISSUE TITLE
elgg 3.3.7 Event Manger v12 show all events on google maps don't work

### ISSUE THREAD

**Issue by mendo79** [ColdTrick/event_manager#161]
Hi,

google maps, to show all events in the map not loading..

**Comment by mendo79** [comment]
it seems to have an error at loading "/action/event_manager/event/search"

**Comment by jdalsem** [comment]
Fixed in https://github.com/ColdTrick/event_manager/commit/51c334b8ccf68153fad3bdcdcc7ab2fddc287f88
