### ISSUE TITLE
Gaelic Translation causing fatal error

### ISSUE THREAD

**Issue by MacMhicheil** [ColdTrick/event_manager#167]
The Gaelic language file appears to be causing a fatal error when I upload it to my site. I think it's to do with some unescaped apostrophes I've noticed in the Gaelic strings. I'll need to have a thorough look for anymore and then I'll submit a new pull request.

**Comment by jdalsem** [comment]
ok... you can try to make the translation file using the Translation Editor plugin. That plugin will help escaping the characters the correct way. https://github.com/ColdTrick/translation_editor

**Comment by jeabakker** [comment]
for now i reverted your previous PR

**Comment by MacMhicheil** [comment]
I've redone the translation using Translation Editor and it's working on my site now with no issues. I've submitted a pull request with the new translation file.
