### ISSUE TITLE
Event Series - Recurring Events

### ISSUE THREAD

**Issue by danabnormal** [ColdTrick/event_manager#17]
Hi! Love the plugin, its exactly what I need... except for recurring events.

I've taken a peek at the code and I'm thinking the easiest way to do it would be an 'Event Series' interface. As an example, you could create an Event Series called Open Mic with a start date and basic generic info, then set a recurrence (daily, weekly, monthly) and end date (max 12 months I think would be OK).

This could then use the existing creation system to create events in the calendar, adding a 'series id' to each entry. The benefit of doing it this way is that theres little change to the existing code (just adding a provision for series ID), and changes can then be made to each actual event (bands that are playing for example). 

If I get a chance I'll attempt a second plugin for this, but whats your thoughts on the method? I tried setting additional days to an event to achieve a similar result but it only lists the first day in the event calendar rather than adding each day separately.

Cheers,

Dan

**Comment by jdalsem** [comment]
Not expecting this making it into Event Manager any time soon
