### ISSUE TITLE
composer conflict

### ISSUE THREAD

**Issue by valmiki** [ColdTrick/event_manager#177]
**Elgg version**
4.3

**Plugin version**
15.0.1

**Plugin source**
- Composer installation

**Describe the bug**
from running: composer require coldtrick/event_manager
"Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - elgg/elgg is locked to version 4.3.0 and an update of this package was not requested.
    - roave/security-advisories dev-master conflicts with dompdf/dompdf v1.2.2.
    - coldtrick/event_manager[v15.0, ..., v15.0.1] require dompdf/dompdf ~1.2.1 -> satisfiable by dompdf/dompdf[v1.2.1, v1.2.2].
    - elgg/elgg 4.3.0 requires roave/security-advisories dev-master -> satisfiable by roave/security-advisories[dev-master].
    - Root composer.json requires coldtrick/event_manager ^15.0 -> satisfiable by coldtrick/event_manager[v15.0, v15.0.1]."

**Expected behavior**
No conflict report.

**Comment by jdalsem** [comment]
This has been fixed in https://github.com/ColdTrick/event_manager/commit/3551706e3274b46f3bd3974291fb00ba3d47195c

You can expect a official release in a few days
