### ISSUE TITLE
Archive listing of past events

### ISSUE THREAD

**Issue by valmiki** [ColdTrick/event_manager#182]
**Is your feature request related to a problem? Please describe.**
We use the event manager for lessons in a course. Beyond a limited number of past events/lessons it is not possible to see them in the dashboard. 

**Describe the solution you'd like**
It would be nice to have a tab that shows past events site wide or belonging to a group. 

**Describe alternatives you've considered**
Provide it via an override. But I think it is a useful feature for many.

**Comment by jdalsem** [comment]
Current listings are focused on upcomming events. Only the calendar view is currently able to show items in the past. We have provided listings with items in the past in previous versions. This caused confusion for various users so we decided to drop it for now.

If you need these kind of listings it would not be hard to add them to your own site with a little programming.

At the moment we have no plans to add these features to this plugin.
