### ISSUE TITLE
Implement calendar view

### ISSUE THREAD

**Issue by jdalsem** [ColdTrick/event_manager#53]
Implement a calendar view like http://fullcalendar.io/

**Comment by michelesbw** [comment]
+1 on this :) what about Ismayil code here? https://github.com/hypeJunction/event_manager_calendar
Just in case you didn't know about it and possible/nice for you to use. Cheers

**Comment by bruno-infotrad** [comment]
Hello Jeroem,
I know there will be a bit of work involved, but if you are interested, you can also have a look at my three column implementation at https://github.com/bruno-infotrad/gc-elgg/tree/1.10.5/mod/gc_theme

**Comment by jdalsem** [comment]
Fixed with https://github.com/ColdTrick/event_manager/commit/678cdb2ca7e879159884ef5bc261fa8570930b5b
