### ISSUE TITLE
Disappearing sets

### ISSUE THREAD

**Issue by juho-jaakkola** [ColdTrick/event_manager#54]
The Elgg 1.9 version:

1. Add three slots, and choose one
2. Save
3. Open the editing page again -> all but the chosen set have disappeared

**Comment by jdalsem** [comment]
This is actually not really a bug. Only the actual used slot set names will be saved. So adding three and using 1 will make the other 2 disappear. The list of available sets is determined based on the uniquely used set names for the event. (metadata saved with the slots).
