### ISSUE TITLE
"On The Map" Tab -> map-points not at correct geo-location

### ISSUE THREAD

**Issue by arischmod** [ColdTrick/event_manager#59]
Hello!
congrats for the project, very very very helpful - so much functionality out of the box!

Im facing a problem and I just wanted to check if any one else has faced it..

The "On The Map" Tab
load my events but it place the map-markers at the centre of earth (shareware left of Africa)!

when I click the address of each event at the "List" Tab the map opens with the Map-Point to the correct spot, that means that the geo-location is properly stored..

**Comment by jdalsem** [comment]
Unfortunately i can not reproduce this issue. If you have more information about this, or a location to reproduce it with, we can try again (and i will reopen the ticket then).
