### ISSUE TITLE
Location popup not showing the map

### ISSUE THREAD

**Issue by rohit1290** [ColdTrick/event_manager#65]
I am using Event Manager 3.0. Whenever I am trying to add the location of the event, the pop window is getting open but instead of a map the create new event page is show inside the popup window.

Kindly help.!

**Comment by jdalsem** [comment]
You could test with the latest github version. There was a bug related to this, that got fixed: https://github.com/ColdTrick/event_manager/commit/6dfee74e3ffbd55fd49c3ef735756d634311607e
