### ISSUE TITLE
Slight imcompatibility with 1.10.3

### ISSUE THREAD

**Issue by Westlake56** [ColdTrick/event_manager#66]
I upgraded my elgg from 1.9.8 to 1.10.3 and for some reason when I post and icon with the event it just shows a box like for a missing image.

Not sure if it's 1.10 or could something else have caused it during the upgrade?

![no icon](https://cloud.githubusercontent.com/assets/11148775/6689912/9a9aaaf2-cc93-11e4-9579-bc5119202877.png)

Dan

**Comment by jdalsem** [comment]
Thanks for reporting
