### ISSUE TITLE
Don’t show "0 attendees" on Events with disabled registration

### ISSUE THREAD

**Issue by Pasley70** [ColdTrick/event_manager#67]
Sometimes it is useful to announce an appointment without attendees (settings: "Disable registration to this event"). In this case, the output "0 Participants" on list- and detail-view is confusing.

**Comment by jdalsem** [comment]
Good catch... fixed it

**Comment by Pasley70** [comment]
Thanx! The Event-Manager Widget (managed by the Widget-Manager) still shows attendees on the index-Page.

![events-screenshot](https://cloud.githubusercontent.com/assets/498312/6727962/567dc676-ce26-11e4-81ff-0e774894c4e5.png)

Is this an issue for the Event-Manger or Widget-Manager?

To view the attendees beneath the RSVP is a very good idea (like in the Screenshot). Is it possible to ad this to the "normal" List-View? Or is it enough to view this in the entity-menu?

**Comment by jdalsem** [comment]
i updated the commit to also hide the attendee count in the widgets (based on the same logic).

**Comment by jdalsem** [comment]
> To view the attendees beneath the RSVP is a very good idea (like in the Screenshot). Is it possible to ad this to the "normal" List-View? Or is it enough to view this in the entity-menu?

This was originally the case, but i moved it to the entity menu for the listing and full views, as i wanted to reduce the amount of custom locations of data. Because of the limited space in widgets it is still intact there
