### ISSUE TITLE
Integrate the Event Submission form  with the Status box

### ISSUE THREAD

**Issue by dranii** [ColdTrick/event_manager#68]
Integrate the Event Submission form [additionally and optionally] with the Status box on the top of Activity page/Profile page. This becomes intuitive for the site member and attractive in an user-friendly way. See a demo of what I mean here : http://easysocial.stackideas.com/

If such form is indeed devised, one has to keep in mind other plugins placing icons around this box eg Hypewall so that an integrated aesthetic eye-candy UI can be there. Relevant forum discussion
https://community.elgg.org/discussion/view/2067799/improve-the-status-box-on-the-top-of-activity-pageprofile-page

Thanks

**Comment by jdalsem** [comment]
This requires first to have an extendable status box feature. I'm not going to add a custom feature just for the Event Manager, so Elgg should first come up with something better for that. This ticket can be reopened when there is a generic approach for that.
