### ISSUE TITLE
Deprecated in 1.9: elgg_get_entities_from_location

### ISSUE THREAD

**Issue by lianglee** [ColdTrick/event_manager#69]
Deprecated in 1.9: elgg_get_entities_from_location is deprecated. See geolocation plugin on github

**Comment by Mark-Bridges** [comment]
Likewise... happens after viewing map and then changing to a new site page.  Can't seem to find the geolocation plugin on github.

**Comment by jdalsem** [comment]
Leaving this as is, as there is currently no good alternative. See also https://github.com/Elgg/Elgg/issues/8253
