### ISSUE TITLE
"Please fill in required fields" despite of all of them being filled in if logged out

### ISSUE THREAD

**Issue by jdalsem** [ColdTrick/event_manager#72]
When adding an event registration form, if there's any mandatory field in it, and trying to register as not logged in (enabled "Allow registration to non logged in users") the registration is not possible, the site keeps throwing the message "Please fill in required fields" despite of all of them being filled in.

Reported on the Elgg community by @michelesbw

**Comment by jdalsem** [comment]
I have tested this with a basic event with 1 registration question (that was required). I am unable to reproduce the issue. 

@michelesbw can you tell/show me your registration form questions? Maybe a different type of field makes the issue reproducible...

**Comment by michelesbw** [comment]
Hello Jeroen,
this is the one whose fields now are all not required due to the issue mentioned: https://socialbusinessworld.org/events/event/register/568404
Cheers
M

**Comment by jdalsem** [comment]
i think i can reproduce it; the issue occurs when you submit the registration form and one of the values = 0. On your registration form you have several questions that require to fill in an amount (a number) and maybe it is sometimes entered with a zero as a value. That is the only way i can reproduce it. Can you confirm that is the same case with you? (Replacing the zero's with something else should make the submissing go through).

**Comment by michelesbw** [comment]
I am pretty sure that could have been the case. Sorry for not testing throughoutly.

**Comment by jdalsem** [comment]
no problem... the issue has been fixed... thanks for reporting
