### ISSUE TITLE
AddEvent error 

### ISSUE THREAD

**Issue by Beaufort8** [ColdTrick/event_manager#73]
If an event is created for Outlook, AddEvent reports following Error: 

The event you have tried to add to your calendar contains invalid date information.
Invalid start date: 2015-10-22 19:00:00. Date does not match date_format → dd/mm/yyyy.

**Comment by jdalsem** [comment]
Can you provide steps to reproduce this (creating a new event). I am currently unable to reproduce this

**Comment by Beaufort8** [comment]
Strangely - after today's test ICS files are generated correct. Probably that was a fault of Web service "addevent.com" last week. You can close that issue.
