### ISSUE TITLE
Event manager 4.0

### ISSUE THREAD

**Issue by olairmarcos** [ColdTrick/event_manager#75]
In all events, the option: (On The map), does not show any information about the events on the map.
Field location and trace route, the map is displayed correctly.

Thanks for help.

**Comment by jdalsem** [comment]
I have no problems what so ever. Are there events that should be on the map? Do you see an ajax call that fetches the events?

**Comment by rohit1290** [comment]
Map not loading. Tried flushing the cache. Cross checked the Google API. Still I am not able to see the map. The browser is just loading the page and showing "Waiting for map.google.com" and after some time the map area is showing "Sorry, We have no imagery here"

![maps - copy](https://cloud.githubusercontent.com/assets/2772844/11786661/c1346a9a-a2ad-11e5-89eb-7c39ac2b1b82.png)

![map2](https://cloud.githubusercontent.com/assets/2772844/11786654/ba0e439e-a2ad-11e5-991c-6c8b62dbda2f.JPG)

**Comment by jdalsem** [comment]
Could you try to save the event manager plugin settings? Maybe that will
reset something internally...

Met vriendelijke groet,

Jeroen Dalsem

ColdTrick IT Solutions
Rigtersbleek Zandvoort 10-1.42
7521 BE Enschede
Tel. 053-7114017
Mob. 06-46068234

2015-12-14 17:28 GMT+01:00 TechBytes with Rohit <notifications@github.com>:

**Comment by rohit1290** [comment]
Done that. I always save the setting after a version update of any plugin.

**Comment by rohit1290** [comment]
This is what I found in my browser console
Google Maps API warning: SensorNotRequired: https://developers.google.com/maps/documentation/javascript/error-messages

**Comment by rohit1290** [comment]
The map failed to load due to the following issue that I found in my browser's console
```
* http://mt1.googleapis.com/maps/vt?pb=!1m5!1m4!1i4!2i11!3i6!4i256!2m3!1e0!2sm!3i332454133!3m9!2sen-US!3sUS!5e18!12m1!1e47!12m3!1e37!2m1!1ssmartmaps!4e0 Failed to load resource: the server responded with a status of 504 (Gateway Time-out)
* http://mt1.googleapis.com/maps/vt?pb=!1m5!1m4!1i4!2i11!3i7!4i256!2m3!1e0!2sm!3i332454133!3m9!2sen-US!3sUS!5e18!12m1!1e47!12m3!1e37!2m1!1ssmartmaps!4e0 Failed to load resource: the server responded with a status of 504 (Gateway Time-out)
* http://mt0.googleapis.com/maps/vt?pb=!1m5!1m4!1i4!2i10!3i7!4i256!2m3!1e0!2sm!3i332454133!3m9!2sen-US!3sUS!5e18!12m1!1e47!12m3!1e37!2m1!1ssmartmaps!4e0 Failed to load resource: the server responded with a status of 504 (Gateway Time-out)
* http://mt0.googleapis.com/maps/vt?pb=!1m5!1m4!1i4!2i12!3i6!4i256!2m3!1e0!2sm!3i332454133!3m9!2sen-US!3sUS!5e18!12m1!1e47!12m3!1e37!2m1!1ssmartmaps!4e0 Failed to load resource: the server responded with a status of 504 (Gateway Time-out)
* http://mt0.googleapis.com/maps/vt?pb=!1m5!1m4!1i4!2i12!3i7!4i256!2m3!1e0!2sm!3i332454133!3m9!2sen-US!3sUS!5e18!12m1!1e47!12m3!1e37!2m1!1ssmartmaps!4e0 Failed to load resource: the server responded with a status of 504 (Gateway Time-out)
* http://mt1.googleapis.com/maps/vt?pb=!1m5!1m4!1i4!2i11!3i5!4i256!2m3!1e0!2sm!3i332454133!3m9!2sen-US!3sUS!5e18!12m1!1e47!12m3!1e37!2m1!1ssmartmaps!4e0 Failed to load resource: the server responded with a status of 504 (Gateway Time-out)
* http://mt1.googleapis.com/maps/vt?pb=!1m4!1m3!1i4!2i10!3i5!1m4!1m3!1i4!2i11…!12m3!1e37!2m1!1ssmartmaps!4e3!12m1!5b1&callback=_xdc_._18zrl4&token=35134 Failed to load resource: the server responded with a status of 504 (Gateway Time-out)
* http://mt1.googleapis.com/maps/vt?pb=!1m5!1m4!1i4!2i11!3i8!4i256!2m3!1e0!2sm!3i332454133!3m9!2sen-US!3sUS!5e18!12m1!1e47!12m3!1e37!2m1!1ssmartmaps!4e0 Failed to load resource: the server responded with a status of 504 (Gateway Time-out)
* http://mt0.googleapis.com/maps/vt?pb=!1m5!1m4!1i4!2i12!3i5!4i256!2m3!1e0!2sm!3i332454133!3m9!2sen-US!3sUS!5e18!12m1!1e47!12m3!1e37!2m1!1ssmartmaps!4e0 Failed to load resource: the server responded with a status of 504 (Gateway Time-out)
* http://mt0.googleapis.com/maps/vt?pb=!1m5!1m4!1i4!2i10!3i5!4i256!2m3!1e0!2sm!3i332454133!3m9!2sen-US!3sUS!5e18!12m1!1e47!12m3!1e37!2m1!1ssmartmaps!4e0 Failed to load resource: the server responded with a status of 504 (Gateway Time-out)
* http://mt0.googleapis.com/maps/vt?pb=!1m5!1m4!1i4!2i10!3i8!4i256!2m3!1e0!2sm!3i332454133!3m9!2sen-US!3sUS!5e18!12m1!1e47!12m3!1e37!2m1!1ssmartmaps!4e0 Failed to load resource: the server responded with a status of 504 (Gateway Time-out)
* http://mt0.googleapis.com/maps/vt?pb=!1m5!1m4!1i4!2i12!3i8!4i256!2m3!1e0!2sm!3i332454133!3m9!2sen-US!3sUS!5e18!12m1!1e47!12m3!1e37!2m1!1ssmartmaps!4e0 Failed to load resource: the server responded with a status of 504 (Gateway Time-out)
```

**Comment by olairmarcos** [comment]
The map is not loaded on the site, it is the same problem that reported above.
Thanks, good work.

**Comment by rohit1290** [comment]
Ok.. Seems like the problem was with the internet connection. Those links were not reachable from the internet connection that i was using yesterday. I tried the same plugin with a different connectivity and everything seems to work fine.

**Comment by jdalsem** [comment]
@olairmarcos if you have the same problem as the original poster please take a look at your internet connection. If you have a different problem please report a new issue with the details of the problem.
