### ISSUE TITLE
Transfer Event to Group from User

### ISSUE THREAD

**Issue by rohit1290** [ColdTrick/event_manager#76]
If I am not wrong then there was a feature in "Event Calendar" for 1.8 where the admin had the option to transfer/add an event to a group that was created as a personal event by user. Can we have the same feature in "Event Manager".

Reason: I am using elgg as a community for students where students can post events. Now many times the user creates a fest/workshop events under their profile as personal events instead of creating it in the college group it should belong to. In such cases, its very useful that the event can later be transfer to the respective college group where the event actually belongs to.

**Comment by rohit1290** [comment]
Kindly let me know when can I expect this feature to be added in the plugin.

**Comment by jdalsem** [comment]
I have no intentions to add this any time soon. If you wish to prioritize the development of this feature, by funding it, you could contact us.

**Comment by rohit1290** [comment]
Thanks for the reply. I have made the necessary changes to use this feature. I will share the source code in few days when I get time and don't worry I will share it for free.

**Comment by rohit1290** [comment]
Here it is.. source code for the feature:
https://github.com/rohit1290/event_manager_feature/commit/7843138161f2385916aab6b43cda508779f48ebf
