### ISSUE TITLE
Fatal error running icon.php 

### ISSUE THREAD

**Issue by gerard-kanters** [ColdTrick/event_manager#77]
When using elgg_solr a fatal error occurs where functions cannot be loaded. Both plugins use /lib/functions to be required_once. Only one is loaded I guess and the solr functions are required in the start script of the plugin. How can this be avoided ? I hacked around the issue by checking if function_exists() but that is not really a good solution.

**Comment by jdalsem** [comment]
This needs fixing as in Elgg 2.0 this is no longer a correct way to include the engine... i let you know when this is fixed... Are you experiencing these problems also in Elgg 1.x??

**Comment by gerard-kanters** [comment]
Thanks, yes it also occurs in 1.x

**Comment by jdalsem** [comment]
Hmmm in 1.x, if both plugins use require_once this should not be causing a problem. Are they both including the same file?

**Comment by gerard-kanters** [comment]
Yes both include lib/functions.php

**Comment by jdalsem** [comment]
Can you point me the conflicting code in the elgg_solr plugin?

**Comment by gerard-kanters** [comment]
Sure, the first native function in solr https://github.com/arckinteractive/elgg_solr/blob/master/start.php#L19

**Comment by jdalsem** [comment]
i expect the problem being in the way require_once is used in elgg_solr. Can you try and rewrite in include lines in elgg_solr to be similar to those in event_manager/start.php?

**Comment by gerard-kanters** [comment]
Indeed that works, so it is a bug in SOLR. Thanks Jeroen. I will make an issue there with the suggested solution
