### ISSUE TITLE
Function name conflict in Elgg 2.2

### ISSUE THREAD

**Issue by juho-jaakkola** [ColdTrick/event_manager#82]
Elgg 2.2 introduced `ElggObject::deleteIcon()` which now conflicts with `Event::deleteIcon()`.

Fatal error: Declaration of Event::deleteIcon() must be compatible with Elgg\EntityIcon::deleteIcon($type = 'icon') in /var/www/elgg/mod/event_manager/classes/Event.php on line 0

**Comment by jdalsem** [comment]
Closed with #83
