### ISSUE TITLE
OS X Safari, Javascript error on map setup

### ISSUE THREAD

**Issue by Beaufort8** [ColdTrick/event_manager#84]
views/default/js/event_manager/maps.js.php line 71

    EventMap.setup = function(element, address, options = {}) {

SyntaxError: Unexpected token '='. Expected a ')' or a ',' after a parameter declaration.

Error occurs only in Safari, not in e.g. Chrome or FireFox.

Perhaps it is better to define the object as:

    EventMap.setup = function(element, address) {
      var options = {};

**Comment by jdalsem** [comment]
Thanks... this saved me searching because maps in Internet Explorer were not working also (and it did not show me any error message)
