### ISSUE TITLE
The views.php paths are wrong when using starter-project

### ISSUE THREAD

**Issue by juho-jaakkola** [ColdTrick/event_manager#85]
When using starter-project to manage an Elgg site, the paths at `views.php` are wrong:
```php
return [
    // viewtype
    'default' => [
       'js/fullcalendar.js' => __DIR__ . '/vendor/bower-asset/fullcalendar/dist/fullcalendar.min.js',
       'js/moment.js' => __DIR__ . '/vendor/bower-asset/moment/min/moment-with-locales.min.js',
       'css/event_manager/fullcalendar.css' => __DIR__ . '/vendor/bower-asset/fullcalendar/dist/fullcalendar.min.css',
    ],
];
```
As the site will install the dependencies to the `vendor/` dir of the site root instead of the plugin directory.

AFAIK they should use this syntax: https://github.com/Elgg/Elgg/blob/2.2/engine/views.php#L8-L10

**Comment by jdalsem** [comment]
Fixed by https://github.com/ColdTrick/event_manager/commit/96b3a0a17cfa6c9e56b45b20f6f73240e4a67ee5
