### ISSUE TITLE
On the map tab doesn't display anything when user is logged out

### ISSUE THREAD

**Issue by michelesbw** [ColdTrick/event_manager#86]
Talking about public events of course, Elgg 2.2, Event Manager 6.0-beta
Cheers

**Comment by jdalsem** [comment]
I can not reproduce this... what is 'nothing'... no map? or no items?

do you get a js error?

**Comment by michelesbw** [comment]
Sorry... please check here https://beta.socialbusinessworld.org/events 
Loader icon spinning, no map shown (only when logged out, logged in works fine).
Cheers

**Comment by jdalsem** [comment]
are you up to date with the latest version? (master branch)... a few things changed the last days

**Comment by michelesbw** [comment]
We're on 6.0-beta updated last week, maybe news in...thanks for replying!

**Comment by michelesbw** [comment]
after latest update seems working fine, thank you!!!
