### ISSUE TITLE
Web Services API

### ISSUE THREAD

**Issue by rohit1290** [ColdTrick/event_manager#87]
Do we have any web services API for the plugin?

**Comment by jdalsem** [comment]
nope

**Comment by rohit1290** [comment]
I am planning to write the web API for Event manager. Can you help me in identify the function name & file where I can find the code for following:

* View all Events
* View details of a particular event
* RSVP Events
* Unsubscribe Events
* Create / Edit an events
* Delete an Event
* Search an event

**Comment by jdalsem** [comment]
just look at the resource files and actions
