### ISSUE TITLE
group custom layout plugin not working with group event pages

### ISSUE THREAD

**Issue by oseg** [ColdTrick/event_manager#90]
context: 
- elgg v2.2.1 & group_custom_layout v3.1 & event_manager v7.2
- also reproduced with elgg v1.12.11 & group_custom_layout v3.1 & event_manager v4.0

scenario:
- Enable group_custom_layout for a test group
- Click on "Edit Group Layout" link on this group profile page
- Set "Enable custom background image" to "yes", select an image and click the "save" button
=> The group profile page is displayed with a custom background
- Click on "group events" link to display the group events page
- Click on the "New event" button
- Create a test event by filling the form & clicking on the "save" button
=> The new group event page is displayed but the group custom background is gone

**Comment by oseg** [comment]
Suggested patch:
call elgg_set_page_owner_guid() before calling elgg_view_resource() in the page_handler.

For instance, In classes\ColdTrick\EventManager\PageHandler.php at line 80
```
case 'event':
	switch ($page[1]) {
		case 'list':
			$owner_guid = (int) elgg_extract(2, $page);
			if ($owner_guid) {
				elgg_set_page_owner_guid($owner_guid);
			}
			echo elgg_view_resource('events/event/list');
			return true;
		case 'view':
                        // begin of patch: add these 3 lines
			$guid = (int) elgg_extract(2, $page);
			$event = get_entity($guid);
			elgg_set_page_owner_guid($event->getContainerGUID());
                        // end of patch
			echo elgg_view_resource('events/event/view', [
				'guid' => (int) elgg_extract(2, $page),
			]);
			return true;
```
But a global solution would better than this local patch, that needs to be applied on all pages reproducing the group custom layout issue

**Comment by jdalsem** [comment]
i believe this is a 'timing' issue that should be solved in group_custom_layout instead of in event_manager

the reason is the unreliability of the page_setup system event

**Comment by oseg** [comment]
Hi Jdalsem,

Thanks for the tip, Sorry for the late answer.

I replaced 'pagesetup' 'system' event registration (deprecated in elgg 2.3) by 'shell' 'page' hook registration as suggested in elgg v2.3 doc, it fixed the issue on following 'http://localhost/events/event/view/214/test-event' page url, as you expected.

But I still got the same issue on another page url "http://localhost/events/registration/view/214". I had a quick look in "resources/events/registration/view.php" called by EventManager\PageHandler, and I didn't see any call to elgg_set_page_owner_guid(). That could be the reason why In my 'shell' 'page' hook, the function elgg_get_page_owner_entity() returns 'false'. What do you think?

Best regards,
Olivier

**Comment by oseg** [comment]
Issue also reproduced on following page url: 'localhost/events/event/upload/214'
