### ISSUE TITLE
End date not saving correctly if selected via dropdown (Elgg 2)

### ISSUE THREAD

**Issue by michelesbw** [ColdTrick/event_manager#91]
Hello,
it seems end date/time is not saved if using dropdown menus for month and day while works if selecting date via arrows.
Cheers

**Comment by jdalsem** [comment]
@michelesbw did you also select a date after switching months? because that is required... only navigating months or years does not change the 'selected' date

i can not reproduce your problem

**Comment by michelesbw** [comment]
I can' replicate it either now...don't know what fixed it sorry but it's fixed :).
