### ISSUE TITLE
Clicking on the search button in an events list replace the "Attending" button by an "Attending" link on all listed events

### ISSUE THREAD

**Issue by oseg** [ColdTrick/event_manager#94]
reproduced in v7.2

**Comment by jdalsem** [comment]
Could you elaborate a bit more (or clarify with a screenshot)?

**Comment by oseg** [comment]
My mistake: I migrate some code from event manager v7.2 into v4.0 to have the new event manager UI ("attending buttons"...) running on elgg 1.12 until we migrate our server in elgg 2.3.

I have this issue with my modifed version of event manager v4.0 running on elgg v1.12 But, I do not reproduce the issue with elgg v2.2.3 + event manager v7.2

Closing this issue, sorry for the inconvenience.

Olivier
