### ISSUE TITLE
showing two upgrade warnings after upgrade event_manager 

### ISSUE THREAD

**Issue by sachinbanugariya** [ColdTrick/event_manager#95]
hello,
how can i  remove that upgrade notifications from uprade bar.

we get that two warning after upgrade our  event_manager to latest version with elgg 2.3.

if we click on that two uprades for upgrade showing upgrade successfull,
then still its showing on upgrade bar.

we dont want to see that upgrade notifications.
so how can we hide or solve that upgrade notifications from  upgrade bar of elgg.

please check attachments.

thanks.
![event_1](https://cloud.githubusercontent.com/assets/22053179/22331066/6ecd67a0-e3ef-11e6-85c5-22df0ab22454.png)
![event_2](https://cloud.githubusercontent.com/assets/22053179/22331069/74dea1cc-e3ef-11e6-8549-ba0932de6424.png)

**Comment by jdalsem** [comment]
They should be removed when the upgrade is finished... i will look into this issue

**Comment by jdalsem** [comment]
Unable to reproduce
