### ISSUE TITLE
Internet-Explorer: Fatal Error when uploading an image

### ISSUE THREAD

**Issue by Beaufort8** [ColdTrick/event_manager#96]
If you upload an Image via Internet-Explorer (testet with IE11; no problem with FF, Safari etc.) you get an PHP-Error:

Call to a member function saveIconFromUploadedFile() on a non-object in /mod/evetnt_manager/actions/event/edit.php on line 102

The event is still created, but without the image.

**Comment by jdalsem** [comment]
i think you ran into a bug that is part of Elgg 2.3. We worked around the bug in this commit https://github.com/ColdTrick/event_manager/commit/1cd662689d59fffbfab68539b05d2e9fc3bf6496

There has been a release (https://github.com/ColdTrick/event_manager/releases/tag/v7.2.1) that contains this fix... maybe you just need to update :)

**Comment by jdalsem** [comment]
Don't know why this would be only with IE though... maybe because of how temp file names are handled...

**Comment by Beaufort8** [comment]
This happens with the latest Version 7.2.1 :-(

**Comment by jdalsem** [comment]
Fixed it... it was not related to IE... it only happened uploading an image during the creation of a new event... uploading to an existing one worked

**Comment by jdalsem** [comment]
We created a release for your convenience... 7.2.2...

**Comment by Beaufort8** [comment]
Fantastic! Thanx!
