### ISSUE TITLE
Call to undefined function elgg_get_uploaded_files() on elgg v2.2.4

### ISSUE THREAD

**Issue by oseg** [ColdTrick/event_manager#98]
Event manager releases v7.2.1 and v7.2.2 running under elgg 2.2.4 crash when saving event edit page because of:
Fatal error:  Call to undefined function elgg_get_uploaded_files() in C:\xampp\htdocs\elgg-2.2.4\mod\event_manager\actions\event\edit.php on line 98

**Comment by jdalsem** [comment]
Best you can do is upgrade to Elgg 2.3
